title: "Holobiont Systems Biology"
email: soon-jae.lee@um6p.ma
description: >- 
  Research on the organizing and functional principles of holobionts, symbiotic communication, and multi‑species chronobiology.
minimal_mistakes_skin: "default"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
paginate: 5 # amount of posts to show
paginate_path: /page:num/
#timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

author:
  name   : "LEE Lab: Holobiont Systems Biology"
  avatar : "/assets/images/lab-logo.png"
  bio    : "We study the organizing principles of holobionts, symbiotic communication, and multi‑species chronobiology."
  links:
    - label: "PI: Prof. Soon-Jae Lee"
      icon: "fas fa-user"
      url: "/PI/"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0002-7216-0236"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=enk-b7IAAAAJ&hl=en"

header:
  overlay_image: /assets/images/summary.png
  overlay_filter: 0.3


footer:
  links:
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0002-7216-0236"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=enk-b7IAAAAJ&hl=en"

google_fonts: "Cormorant+Garamond:400,600|Lato:300,400,700"


defaults:
  # _posts
  #- scope:
  #    path: "_pages"
  #    type: pages
  #  values:
  #    layout: single
  #    author_profile: false
      #read_time: true
      #comments: true
      #share: true
      #related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: splash
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
